Database_Coursework_MVC/Controllers/AddressController.cs
using Database_Coursework_MVC.Interface;
using Database_Coursework_MVC.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Database_Coursework_MVC.Controllers
{
    public class AddressController : Controller
    {
        private readonly IAddressRepo _addressService;
        public AddressController (IAddressRepo addressService)
        {
            _addressService = addressService;
        }
        public IActionResult Index()
        {
            IEnumerable<AddressModel> address = _addressService.GetAllAddresses();
            return View(address);
        }
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(AddressModel address)
        {
            _addressService.AddAddress(address);
            return RedirectToAction(nameof(Index));
        }
        public IActionResult Edit(int id)
        {
            AddressModel address = _addressService.GetAddressById(id);
            return View(address);
        }

        [HttpPost]
        public IActionResult Edit(AddressModel address)
        {
            _addressService.EditAddress(address);
            return RedirectToAction(nameof(Index));
        }
        public IActionResult Delete(int id)
        {
            AddressModel address = _addressService.GetAddressById(id);
            return View(address);
        }

        // POST: DeleteTestController/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, AddressModel addressModel)
        {
            try
            {
                AddressModel address = _addressService.GetAddressById(id);
                _addressService.DeleteAddress(address);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Database_Coursework_MVC/Controllers/ModuleController.cs
using Database_Coursework_MVC.Interface;
using Database_Coursework_MVC.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Database_Coursework_MVC.Controllers
{
    public class ModuleController : Controller
    {
        IModuleRepo moduleService;
        public ModuleController (IModuleRepo _moduleService)
        {
            moduleService = _moduleService;
        }
        public IActionResult Index()
        {
            IEnumerable<ModuleModel> module = moduleService.GetAllModules();
            return View(module);
        }
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(ModuleModel module)
        {
            moduleService.AddModule(module);
            return RedirectToAction(nameof(Index));
        }
        public IActionResult Edit(int id)
        {
            ModuleModel module = moduleService.GetModuleById(id);
            return View(module);
        }

        [HttpPost]
        public IActionResult Edit(ModuleModel module)
        {
            moduleService.EditModule(module);
            return RedirectToAction(nameof(Index));
        }
        public IActionResult Delete(int id)
        {
            ModuleModel module = moduleService.GetModuleById(id);
            return View(module);
        }
        [HttpPost]
        public ActionResult Delete(int id, ModuleModel moduleModel)
        {
            try
            {
                ModuleModel module = moduleService.GetModuleById(id);
                moduleService.DeleteModule(module);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Database_Coursework_MVC/Controllers/StudentController.cs
using Database_Coursework_MVC.Interface;
using Database_Coursework_MVC.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Database_Coursework_MVC.Controllers
{
    public class StudentController : Controller
    {
        IStudentRepo studentService;
        public StudentController(IStudentRepo _studentService)
        {
            studentService = _studentService;
        }
        public IActionResult Index()
        {
            IEnumerable<StudentModel> student = studentService.GetAllStudent();
            return View(student);
        }
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(StudentModel student)
        {
            studentService.AddStudent(student);
            return RedirectToAction(nameof(Index));
        }
        public IActionResult Edit(int id)
        {
            StudentModel student = studentService.GetStudentById(id);
            return View(student);
        }
        [HttpPost]
        public IActionResult Edit(StudentModel student)
        {
            studentService.EditStudent(student);
            return RedirectToAction(nameof(Index));
        }
        public IActionResult Delete(int id)
        {
            StudentModel student = studentService.GetStudentById(id);
            return View(student);
        }
        [HttpPost]
        public ActionResult Delete(int id, StudentModel studenModel)
        {
            try
            {
                StudentModel student = studentService.GetStudentById(id);
                studentService.DeleteStudent(student);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Database_Coursework_MVC/Controllers/TeacherController.cs
using Database_Coursework_MVC.Interface;
using Database_Coursework_MVC.Models;
using Database_Coursework_MVC.Services;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Database_Coursework_MVC.Controllers
{
    public class TeacherController : Controller
    {
        ITeacherRepo teacherService;
        public TeacherController(ITeacherRepo _teacherService)
        {
            teacherService = _teacherService;
        }
        public IActionResult Index()
        {
            IEnumerable<TeacherModel> teacher = teacherService.GetAllTeacher();
            return View(teacher);
        }
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(TeacherModel teacher)
        {
            teacherService.AddTeacher(teacher);
            return RedirectToAction(nameof(Index));
        }
        public IActionResult Edit(int id)
        {
            TeacherModel teacher = teacherService.GetTeacherById(id);
            return View(teacher);
        }

        [HttpPost]
        public IActionResult Edit(TeacherModel teacher)
        {
            teacherService.EditTeacher(teacher);
            return RedirectToAction(nameof(Index));
        }
        public IActionResult Delete(int id)
        {
            TeacherModel teacher = teacherService.GetTeacherById(id);
            return View(teacher);
        }
        [HttpPost]
        public ActionResult Delete(int id, TeacherModel teacherModel)
        {
            try
            {
                TeacherModel teacher = teacherService.GetTeacherById(id);
                teacherService.DeleteTeacher(teacher);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Database_Coursework_MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - School Management System</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@500&family=Raleway:wght@600&family=Roboto:wght@500&display=swap" rel="stylesheet">
    <style>
        body {
            font-family: 'Montserrat', sans-serif !important;
        }

        .nav-item a {
            transition: all 0.4s;
            margin: auto 1rem !important;
            font-size: 0.7rem;
        }

        .nav-item:hover {
            border-bottom: 1px solid white;
            margin-top: -1px !important;
        }

            .nav-item:hover a {
                color: lightblue !important;
                font-size: 0.7rem;
            }
        .navbar-brand {
            transition: all 1s !important;
        }

            .navbar-brand:hover {
                color: lightblue !important;
            }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container p-2">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav mr-auto ml-auto nav-bar">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">HOME</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Student" asp-action="Index">STUDENT</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Teacher" asp-action="Index">TEACHER</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Module" asp-action="Index">MODULE</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Department" asp-action="Index">DEPARTMENT</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Address" asp-action="Index">ADDRESS</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted bg-dark">
        <div class="container">
            &copy; 2022 - Powered by - <a href="http://www.github.com/nimeshmaharjan1">Nimesh Maharjan</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>