Database_Coursework_MVC/Controllers/AddressController.cs
using Database_Coursework_MVC.Interface;
using Database_Coursework_MVC.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Database_Coursework_MVC.Controllers
{
    public class AddressController : Controller
    {
        private readonly IAddressRepo _addressService;
        public AddressController (IAddressRepo addressService)
        {
            _addressService = addressService;
        }
        public IActionResult Index()
        {
            IEnumerable<AddressModel> address = _addressService.GetAllAddresses();
            return View(address);
        }
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(AddressModel address)
        {
            _addressService.AddAddress(address);
            return RedirectToAction(nameof(Index));
        }
        public IActionResult Edit(int id)
        {
            AddressModel address = _addressService.GetAddressById(id);
            return View(address);
        }

        [HttpPost]
        public IActionResult Edit(AddressModel address)
        {
            _addressService.EditAddress(address);
            return RedirectToAction(nameof(Index));
        }
        public IActionResult Delete(int id)
        {
            AddressModel address = _addressService.GetAddressById(id);
            return View(address);
        }

        // POST: DeleteTestController/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, AddressModel addressModel)
        {
            try
            {
                AddressModel address = _addressService.GetAddressById(id);
                _addressService.DeleteAddress(address);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Database_Coursework_MVC/Controllers/FeeController.cs
using Database_Coursework_MVC.Interface;
using Database_Coursework_MVC.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Database_Coursework_MVC.Controllers
{
    public class FeeController : Controller
    {
        private IFeeDepartmentRepo feeService;
        public FeeController(IFeeDepartmentRepo _feeService)
        {
            feeService = _feeService;
        }
        public IActionResult Index()
        {
            IEnumerable<FeeModel> fee = feeService.GetAllFee();
            return View(fee);
        }
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(FeeModel fee)
        {
            feeService.AddFee(fee);
            return RedirectToAction(nameof(Index));
        }
        public IActionResult Edit(int id)
        {
            FeeModel fee = feeService.GetFeeById(id);
            return View(fee);
        }

        [HttpPost]
        public IActionResult Edit(FeeModel fee)
        {
            feeService.EditFee(fee);
            return RedirectToAction(nameof(Index));
        }
        public IActionResult Delete(int id)
        {
            FeeModel fee = feeService.GetFeeById(id);
            //feeService.DeleteFee(fee);
            //return RedirectToAction(nameof(Index));
            return View(fee);
        }
        [HttpPost]
        public ActionResult Delete(int id, FeeModel feeModel)
        {
            try
            {
                FeeModel fee = feeService.GetFeeById(id);
                feeService.DeleteFee(fee);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Database_Coursework_MVC/Controllers/HomeController.cs
using Database_Coursework_MVC.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Database_Coursework_MVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Database_Coursework_MVC/Controllers/ModuleController.cs
using Database_Coursework_MVC.Interface;
using Database_Coursework_MVC.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Database_Coursework_MVC.Controllers
{
    public class ModuleController : Controller
    {
        IModuleRepo moduleService;
        public ModuleController (IModuleRepo _moduleService)
        {
            moduleService = _moduleService;
        }
        public IActionResult Index()
        {
            IEnumerable<ModuleModel> module = moduleService.GetAllModules();
            return View(module);
        }
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(ModuleModel module)
        {
            moduleService.AddModule(module);
            return RedirectToAction(nameof(Index));
        }
        public IActionResult Edit(int id)
        {
            ModuleModel module = moduleService.GetModuleById(id);
            return View(module);
        }

        [HttpPost]
        public IActionResult Edit(ModuleModel module)
        {
            moduleService.EditModule(module);
            return RedirectToAction(nameof(Index));
        }
        public IActionResult Delete(int id)
        {
            ModuleModel module = moduleService.GetModuleById(id);
            return View(module);
        }
        [HttpPost]
        public ActionResult Delete(int id, ModuleModel moduleModel)
        {
            try
            {
                ModuleModel module = moduleService.GetModuleById(id);
                moduleService.DeleteModule(module);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Database_Coursework_MVC/Controllers/StudentController.cs
using Database_Coursework_MVC.Interface;
using Database_Coursework_MVC.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Database_Coursework_MVC.Controllers
{
    public class StudentController : Controller
    {
        IStudentRepo studentService;
        public StudentController(IStudentRepo _studentService)
        {
            studentService = _studentService;
        }
        public IActionResult Index()
        {
            IEnumerable<StudentModel> student = studentService.GetAllStudent();
            return View(student);
        }
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(StudentModel student)
        {
            studentService.AddStudent(student);
            return RedirectToAction(nameof(Index));
        }
        public IActionResult Edit(int id)
        {
            StudentModel student = studentService.GetStudentById(id);
            return View(student);
        }
        [HttpPost]
        public IActionResult Edit(StudentModel student)
        {
            studentService.EditStudent(student);
            return RedirectToAction(nameof(Index));
        }
        public IActionResult Delete(int id)
        {
            StudentModel student = studentService.GetStudentById(id);
            return View(student);
        }
        [HttpPost]
        public ActionResult Delete(int id, StudentModel studenModel)
        {
            try
            {
                StudentModel student = studentService.GetStudentById(id);
                studentService.DeleteStudent(student);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Database_Coursework_MVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<style>
    * {
        scroll-behavior: smooth;
    }

    .card-header h1, h4 {
        opacity: 0.4 !important;
        margin-top: 0.5rem;
    }

    .card {
        box-shadow: 5px 5px 5px 0px rgba(0,0,0,0.3);
        filter: drop-shadow(5px 5px 5px rgba(0,0,0,0.3));
    }
</style>
<div class="card mt-4">
    <div class="card-header bg-dark text-white text-center">
        <h1 class="font-weight-bold">Welcome</h1>
    </div>
    <div class="card-body">
        <div class="row align-items-center">
            <div class="col-md-6 text-center">
                <img style="height: 300px" src="~/assets/logo.svg" alt="Logo"/>
            </div>
            <div class="col-md-6">
                <h3 class="font-weight-bold">School Management System</h3>
                <p class="text-justify" style="line-height:1.9em">
                    This web-based application has been created to manage various CRUD operations i.e. create, read, update and delete between entities and models in an college environment. Please feel free to surf through the different web forms listed in the website.
                </p>
            </div>
        </div>

    </div>
</div>
<div class="row mt-5 mb-4 justify-content-center">
    <div class="col-md-6">
        <div class="card text-white bg-dark">
            <div class="card-header text-center">
                <h4 class="font-weight-bold">Basic Web Forms</h4>
            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item">
                    <a class="nav-link" asp-area="" asp-controller="Student" asp-action="Index">Student</a>
                </li>
                <li class="list-group-item"><a class="nav-link" asp-area="" asp-controller="Teacher" asp-action="Index">Teacher</a></li>
                <li class="list-group-item"><a class="nav-link" asp-area="" asp-controller="Module" asp-action="Index">Module</a></li>
                <li class="list-group-item"><a class="nav-link" asp-area="" asp-controller="Fee" asp-action="Index">Fee</a></li>
                <li class="list-group-item"><a class="nav-link" asp-area="" asp-controller="Address" asp-action="Index">Address</a></li>
            </ul>
        </div>
    </div>
    <div class="col-md-6">
        <div class="card text-white bg-dark">
            <div class="card-header text-center">
                <h4 class="font-weight-bold">Complex Web Forms</h4>
            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item">
                    <a class="nav-link" asp-area="" asp-controller="TeacherModule" asp-action="Index">Teacher Module Details</a>
                </li>
                <li class="list-group-item">
                    <a class="nav-link" asp-area="" asp-controller="StudentFee" asp-action="Index">Student Fee Payment Details</a>
                </li>
                <li class="list-group-item">
                    <a class="nav-link" asp-area="" asp-controller="StudentAssignment" asp-action="Index">Student Assignment Details</a>
                </li>
            </ul>
        </div>
    </div>
</div>